# Generated by Django 4.2.2 on 2023-07-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default='', max_length=50)),
                ('client_phonenumber', models.CharField(default='', max_length=15)),
                ('client_problem', models.TextField(default='')),
                ('client_location', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='UstaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=65)),
                ('fname', models.CharField(default='', max_length=65)),
                ('phone_number', models.CharField(default='', max_length=15)),
                ('price', models.TextField(default='')),
            ],
            options={
                'db_table': 'usta',
            },
        ),
    ]
